"""Catálogo M25 — 6 games em 3 fases (Grau A, reutiliza datasets NKOS)."""
from __future__ import annotations

GAMES_CATALOG: list[dict] = [
    {
        "entity_code": "GAM_QUIZ_BATTLE_001",
        "slug": "quiz-battle",
        "route": "/games/quiz-battle",
        "phase": 1,
        "phase_label_pt": "Quiz battle & flashcard streak",
        "mechanic": "quiz_battle",
        "title_pt": "Quiz Battle",
        "description_pt": "Duelo de perguntas clínicas com timer e ranking semanal.",
        "datasets": ["datasets/education/quizzes.json"],
        "min_records": 10,
        "xp_per_win": 50,
        "max_rounds": 10,
    },
    {
        "entity_code": "GAM_FLA_STREAK_001",
        "slug": "flash-streak",
        "route": "/games/flash-streak",
        "phase": 1,
        "phase_label_pt": "Quiz battle & flashcard streak",
        "mechanic": "flashcard_streak",
        "title_pt": "Flash Streak",
        "description_pt": "Sequência de acertos em flashcards — mantenha o streak vivo.",
        "datasets": ["datasets/education/flashcards.json"],
        "min_records": 50,
        "xp_per_streak": 10,
        "streak_bonus_at": 5,
    },
    {
        "entity_code": "GAM_SIM_CASE_001",
        "slug": "caso-clinico",
        "route": "/games/caso-clinico",
        "phase": 2,
        "phase_label_pt": "Simulador clínico gamificado",
        "mechanic": "clinical_case",
        "title_pt": "Caso Clínico",
        "description_pt": "Simulados gamificados com feedback imediato e pontuação COREN.",
        "datasets": ["datasets/education/simulated_exams.json"],
        "min_records": 5,
        "xp_per_exam": 120,
    },
    {
        "entity_code": "GAM_ESCALA_SPEED_001",
        "slug": "escala-rapida",
        "route": "/games/escala-rapida",
        "phase": 2,
        "phase_label_pt": "Simulador clínico gamificado",
        "mechanic": "scale_speed",
        "title_pt": "Escala Rápida",
        "description_pt": "Calcule escalas clínicas contra o relógio (GCS, Braden, NEWS2…).",
        "datasets": ["datasets/clinical/calculator_definitions.json", "datasets/clinical/clinical_tools_catalog.json"],
        "min_records": 10,
        "time_limit_sec": 90,
        "xp_per_perfect": 80,
    },
    {
        "entity_code": "GAM_TRILHA_XP_001",
        "slug": "trilhas-xp",
        "route": "/games/trilhas-xp",
        "phase": 3,
        "phase_label_pt": "Trilhas, badges, ranking",
        "mechanic": "path_xp",
        "title_pt": "Trilhas XP",
        "description_pt": "Badges, leaderboard e desafio semanal sobre trilhas de aprendizado.",
        "datasets": ["datasets/education/learning_paths.json"],
        "min_records": 5,
        "features": ["badges", "leaderboard", "weekly_challenge"],
        "badges": [
            {"code": "BDG.FIRST_STEP", "label_pt": "Primeiro passo", "xp": 25},
            {"code": "BDG.WEEK_WARRIOR", "label_pt": "Guerreiro semanal", "xp": 100},
            {"code": "BDG.MASTER_PATH", "label_pt": "Trilha completa", "xp": 250},
        ],
    },
    {
        "entity_code": "GAM_INDICADOR_BOSS_001",
        "slug": "gestor-boss",
        "route": "/games/gestor-boss",
        "phase": 3,
        "phase_label_pt": "Trilhas, badges, ranking",
        "mechanic": "indicator_boss",
        "title_pt": "Gestor Boss",
        "description_pt": "Gamificação de indicadores de enfermagem — meta vs benchmark NDNQI.",
        "datasets": ["datasets/operations/nursing_indicators.json"],
        "min_records": 50,
        "boss_levels": 5,
        "xp_per_level": 150,
    },
]

TARGET_GAMES = len(GAMES_CATALOG)
TARGET_PHASES = 3
