"""Catálogo NKOS — 100 indicadores de enfermagem (NDNQI / COFEN / JCI)."""
from __future__ import annotations

# (code, name_pt, unit_pt, direction)
INDICATOR_CATALOG: list[tuple[str, str, str, str]] = [
    # —— 30 seed (fase 10.7) ——
    ("IND.FALL.RATE", "Taxa de quedas", "quedas por 1000 pacientes-dia", "lower_better"),
    ("IND.FALL.INJURY", "Quedas com dano", "% das quedas", "lower_better"),
    ("IND.PRESSURE.INJURY", "Incidência de lesão por pressão", "% pacientes", "lower_better"),
    ("IND.PRESSURE.STAGE2", "Lesão por pressão estágio ≥2", "por 1000 pacientes-dia", "lower_better"),
    ("IND.MED.ERROR", "Erros de medicação", "por 1000 doses", "lower_better"),
    ("IND.MED.RECONCILIATION", "Reconciliação medicamentosa na admissão", "%", "higher_better"),
    ("IND.HAND.HYGIENE", "Adesão à higiene das mãos", "%", "higher_better"),
    ("IND.PAIN.ASSESS", "Avaliação de dor documentada", "%", "higher_better"),
    ("IND.SAE.COMPLETION", "Conclusão da SAE", "%", "higher_better"),
    ("IND.SAE.DIAGNOSIS", "Diagnósticos de enfermagem registrados", "%", "higher_better"),
    ("IND.CVC.INFECTION", "Infecção de corrente sanguínea associada a CVC", "por 1000 cateter-dia", "lower_better"),
    ("IND.CAUTI.RATE", "ITU associada a cateter vesical", "por 1000 cateter-dia", "lower_better"),
    ("IND.VAP.RATE", "Pneumonia associada à VM", "por 1000 VM-dia", "lower_better"),
    ("IND.PHLEBITIS", "Taxa de flebite", "% acessos periféricos", "lower_better"),
    ("IND.EXTUBATION.ACCIDENTAL", "Extubação acidental", "por 1000 VM-dia", "lower_better"),
    ("IND.RESTRAINT", "Uso de contenção mecânica", "% pacientes-dia", "lower_better"),
    ("IND.STAFF.RATIO", "Razão enfermeiro/paciente", "ratio", "context"),
    ("IND.SKILL.MIX", "Skill mix (enfermeiro/total)", "%", "context"),
    ("IND.OVERTIME", "Horas extras de enfermagem", "% das horas", "lower_better"),
    ("IND.ABSENTEEISM", "Absenteísmo da equipe", "%", "lower_better"),
    ("IND.TURNOVER", "Rotatividade da equipe", "%", "lower_better"),
    ("IND.READMISSION", "Readmissão em 30 dias", "%", "lower_better"),
    ("IND.LOS", "Tempo médio de permanência", "dias", "lower_better"),
    ("IND.MORTALITY", "Mortalidade institucional", "%", "lower_better"),
    ("IND.SEPSIS.BUNDLE", "Adesão ao bundle de sepse (1h)", "%", "higher_better"),
    ("IND.EARLY.WARNING", "Acionamento de time de resposta rápida", "por 1000 pacientes-dia", "context"),
    ("IND.SATISFACTION", "Satisfação do paciente", "score 0-100", "higher_better"),
    ("IND.DISCHARGE.EDU", "Orientação de alta documentada", "%", "higher_better"),
    ("IND.NUTRITION.SCREEN", "Triagem nutricional na admissão", "%", "higher_better"),
    ("IND.VTE.PROPHYLAXIS", "Profilaxia de TEV quando indicada", "%", "higher_better"),
    # —— 70 expansão M21 (documentação, IPC, segurança, perioperatório, etc.) ——
    ("IND.SAE.REASSESS", "Reavaliação da SAE no prazo", "%", "higher_better"),
    ("IND.CARE.PLAN", "Plano de cuidados individualizado documentado", "%", "higher_better"),
    ("IND.NURSING.NOTE", "Evolução de enfermagem por turno", "%", "higher_better"),
    ("IND.INCIDENT.REPORT", "Notificação de incidentes no prazo regulatório", "%", "higher_better"),
    ("IND.NEAR.MISS", "Registro de quase-eventos", "por 1000 pacientes-dia", "context"),
    ("IND.CLABSI.RATE", "CLABSI — infecção de corrente sanguínea", "por 1000 cateter-dia", "lower_better"),
    ("IND.SSUR.RATE", "Infecção de sítio cirúrgico", "% procedimentos", "lower_better"),
    ("IND.MRSA.SCREEN", "Rastreio MRSA na admissão (UTI)", "% elegíveis", "higher_better"),
    ("IND.ISOLATION.COMPLIANCE", "Adesão a precauções de isolamento", "%", "higher_better"),
    ("IND.DEVICE.DAYS", "Dispositivos invasivos monitorados", "dispositivo-dia", "context"),
    ("IND.CATHETER.REMOVAL", "Retirada oportuna de CVC", "% elegíveis", "higher_better"),
    ("IND.URINARY.CATH.REMOVAL", "Retirada oportuna de SVD", "% elegíveis", "higher_better"),
    ("IND.VENT.BUNDLE", "Bundle de VM (cabeceira, sedação, desmame)", "%", "higher_better"),
    ("IND.DIABETES.HYPO", "Episódios de hipoglicemia", "por 1000 pacientes-dia", "lower_better"),
    ("IND.WANDERING.RISK", "Pacientes com risco de fuga monitorados", "%", "higher_better"),
    ("IND.SUICIDE.SCREEN", "Triagem de risco suicida (PSI)", "% admissões", "higher_better"),
    ("IND.DELIRIUM.SCREEN", "Triagem de delirium (CAM/ICU)", "% UTI elegíveis", "higher_better"),
    ("IND.BRADEN.REASSESS", "Reavaliação escala Braden no prazo", "%", "higher_better"),
    ("IND.MORSE.REASSESS", "Reavaliação escala Morse no prazo", "%", "higher_better"),
    ("IND.PAIN.REASSESS", "Reavaliação de dor pós-analgesia", "%", "higher_better"),
    ("IND.FALL.FOLLOWUP", "Plano pós-queda implementado", "% quedas", "higher_better"),
    ("IND.MED.DOUBLECHECK", "Dupla checagem — medicamentos alta vigilância", "% doses", "higher_better"),
    ("IND.MED.LABEL", "Etiquetagem correta de medicamentos", "% amostras", "higher_better"),
    ("IND.TRANSFER.CHECKLIST", "Checklist de transferência intersetorial", "% transferências", "higher_better"),
    ("IND.HANDOFF.SBAR", "Handoff SBAR documentado", "% passagens", "higher_better"),
    ("IND.DISCHARGE.CALL", "Contato pós-alta (48–72 h)", "% altas", "higher_better"),
    ("IND.READMIT.PREVENT", "Plano de prevenção de readmissão", "% alto risco", "higher_better"),
    ("IND.LOS.OUTLIER", "Permanência acima do esperado (outliers)", "% internações", "lower_better"),
    ("IND.OR.TIMEOUT", "Time-out cirúrgico realizado", "% cirurgias", "higher_better"),
    ("IND.OR.SITE.MARK", "Marcação de sítio cirúrgico", "% procedimentos", "higher_better"),
    ("IND.OR.ANTIBIOTIC", "Antibioticoprofilaxia no tempo certo", "% elegíveis", "higher_better"),
    ("IND.OR.HAIR.REMOVAL", "Tricotomia conforme protocolo", "% cirurgias", "higher_better"),
    ("IND.OR.TEMP.MANAGE", "Normotermia perioperatória", "% casos", "higher_better"),
    ("IND.OR.DVT.PROPH", "Profilaxia TEV cirúrgica", "% elegíveis", "higher_better"),
    ("IND.LABOR.ADMISSION", "Avaliação obstétrica na admissão", "% parturientes", "higher_better"),
    ("IND.LABOR.PARTO.HUMAN", "Práticas de parto humanizado documentadas", "% partos", "higher_better"),
    ("IND.NEONATAL.FALL", "Eventos de segurança neonatal", "por 1000 RN-dia", "lower_better"),
    ("IND.BREASTFEED.INIT", "Início precoce da amamentação", "% RN termo", "higher_better"),
    ("IND.KANGAROO.CARE", "Método canguru quando indicado", "% RN elegíveis", "higher_better"),
    ("IND.APGAR.DOCUMENT", "Registro de Apgar completo", "% RN", "higher_better"),
    ("IND.RESTRAINT.ALTERNATIVES", "Alternativas à contenção tentadas", "% contenções", "higher_better"),
    ("IND.RESTRAINT.REASSESS", "Reavaliação de contenção (≤1 h)", "%", "higher_better"),
    ("IND.DEPRESSION.SCREEN", "Triagem de depressão (PHQ-2/9)", "% admissões", "higher_better"),
    ("IND.ALCOHOL.WITHDRAW", "Escala CIWA/CAGE documentada", "% elegíveis", "higher_better"),
    ("IND.ORAL.HYGIENE", "Higiene oral (VM/UTI)", "% turnos", "higher_better"),
    ("IND.MOBILITY.ENCOURAGE", "Mobilização precoce documentada", "% pacientes", "higher_better"),
    ("IND.DELAYED.VOID", "Retenção urinária monitorada", "% cateterizados", "lower_better"),
    ("IND.CONSTIPATION.RISK", "Avaliação de risco de constipação", "% internados", "higher_better"),
    ("IND.FLUID.BALANCE", "Balanço hídrico por turno", "% pacientes críticos", "higher_better"),
    ("IND.WEIGHT.MONITOR", "Monitorização de peso (nutrição)", "% elegíveis", "higher_better"),
    ("IND.CPOT.ASSESS", "Avaliação CPOT (dor/sedação UTI)", "% VM", "higher_better"),
    ("IND.COMFORT.SCORE", "Escala de conforto (UTI)", "% pacientes", "higher_better"),
    ("IND.PALLIATIVE.REFERR", "Referenciamento a cuidados paliativos", "% elegíveis", "higher_better"),
    ("IND.ADVANCE.DIRECTIVE", "Diretivas antecipadas documentadas", "% admissões", "higher_better"),
    ("IND.BURN.CARE", "Curativos de queimados no prazo", "% curativos", "higher_better"),
    ("IND.DIALYSIS.ACCESS", "Acesso de hemodiálise sem infecção", "por 1000 acesso-dia", "lower_better"),
    ("IND.CHEMO.SAFE", "Administração quimioterápica — 9 Rights", "% sessões", "higher_better"),
    ("IND.ONC.PAIN.PLAN", "Plano de dor oncológica atualizado", "% pacientes", "higher_better"),
    ("IND.ED.TRIAGE", "Tempo até triagem na urgência", "minutos (mediana)", "lower_better"),
    ("IND.ED.DOOR.TO.ECG", "Porta-ECG em síndrome coronariana", "minutos (mediana)", "lower_better"),
    ("IND.ED.OVERCROWD", "Taxa de lotação do pronto-atendimento", "% capacidade", "lower_better"),
    ("IND.ICU.MORTALITY.SMR", "Razão mortalidade padronizada UTI", "SMR", "lower_better"),
    ("IND.RRT.ACTIVATION", "Tempo de resposta do RRT", "minutos (mediana)", "lower_better"),
    ("IND.CODE.BLUE.DOC", "Registro completo de parada cardíaca", "% eventos", "higher_better"),
    ("IND.TELEHEALTH.ACCESS", "Teleconsulta de enfermagem realizada", "% elegíveis", "higher_better"),
    ("IND.EHR.ALERT.RESPONSE", "Resposta a alertas clínicos no prontuário", "% alertas", "higher_better"),
    ("IND.NCPD.HOURS", "Horas de educação continuada por profissional", "horas/ano", "higher_better"),
    ("IND.COMPETENCY.VALID", "Competências validadas anualmente", "% equipe", "higher_better"),
    ("IND.MENTORSHIP.HOURS", "Horas de preceptoria por residente", "horas/mês", "higher_better"),
    ("IND.BURNOUT.SCREEN", "Triagem de burnout da equipe", "% equipe/ano", "context"),
]

TARGET_COUNT = 100
