#!/usr/bin/env python3
"""
generate_i18n.py — Gera dicionarios i18n para todos os 30 idiomas do site.
"""
import json, os, copy

with open('i18n/en.json', 'r', encoding='utf-8') as f:
    EN = json.load(f)

COMPACT_UI = {
    "fr": {"nav.inicio":"Accueil","nav.assistencia":"Soins","nav.educacao":"Education","nav.faleconosco":"Contact","nav.pesquisa":"Rechercher","nav.idiomas":"Langues","nav.ferramentas":"Outils","nav.gestao":"Gestion","nav.recursos":"Ressources","nav.institucional":"Institutionnel","nav.entrar":"Connexion","nav.criar":"Creer un compte","aria.busca":"Ouvrir la recherche","aria.idiomas":"Selectionner la langue","aria.menu":"Ouvrir le menu","aria.fechar":"Fermer","aria.navPrincipal":"Navigation principale","content.avaliar":"Evaluer ce contenu","content.compartilhar":"Partager","content.salvar":"Enregistrer","content.imprimir":"Imprimer","content.leitura":"Ecouter","a11y.tituloModal":"Preferences d'accessibilite","a11y.fonteTitulo":"Taille de police","a11y.contrasteTitulo":"Contraste eleve","a11y.temaTitulo":"Mode sombre","a11y.redefinir":"Tout reinitialiser","cookie.aviso":"Avis sur les cookies","cookie.personalizar":"Personnaliser","cookie.rejeitar":"Rejeter non essentiels","cookie.aceiter":"Tout accepter","cookie.salvar":"Enregistrer les preferences","footer.direitos":"Tous droits reserves.","hero.title":"Calculatrices Infirmieres","hero.badge":"Plateforme Globale","seo.h1":"Calculatrices Infirmieres, Examens d'Entrainement et Echelles Cliniques"},
    "de": {"nav.inicio":"Startseite","nav.assistencia":"Pflege","nav.educacao":"Bildung","nav.faleconosco":"Kontakt","nav.pesquisa":"Suche","nav.idiomas":"Sprachen","nav.ferramentas":"Werkzeuge","nav.gestao":"Verwaltung","nav.recursos":"Ressourcen","nav.institucional":"Institutionell","nav.entrar":"Anmelden","nav.criar":"Konto erstellen","aria.busca":"Suche offnen","aria.idiomas":"Sprache wahlen","aria.menu":"Menu offnen","aria.fechar":"Schliessen","aria.navPrincipal":"Hauptnavigation","content.avaliar":"Inhalt bewerten","content.compartilhar":"Teilen","content.salvar":"Speichern","content.imprimir":"Drucken","content.leitura":"Anhoren","a11y.tituloModal":"Barrierefreiheit-Einstellungen","a11y.fonteTitulo":"Schriftgrosse","a11y.contrasteTitulo":"Hoher Kontrast","a11y.temaTitulo":"Dunkelmodus","a11y.redefinir":"Alle zurucksetzen","cookie.aviso":"Cookie-Hinweis","cookie.personalizar":"Anpassen","cookie.rejeitar":"Nicht essentielle ablehnen","cookie.aceiter":"Alle akzeptieren","cookie.salvar":"Einstellungen speichern","footer.direitos":"Alle Rechte vorbehalten.","hero.title":"Pflegerechner","hero.badge":"Globale Plattform","seo.h1":"Pflegerechner, Ubungsprufungen und klinische Skalen"},
    "it": {"nav.inicio":"Home","nav.assistencia":"Assistenza","nav.educacao":"Educazione","nav.faleconosco":"Contatto","nav.pesquisa":"Cerca","nav.idiomas":"Lingue","nav.ferramentas":"Strumenti","nav.gestao":"Gestione","nav.recursos":"Risorse","nav.institucional":"Istituzionale","nav.entrar":"Accedi","nav.criar":"Crea account","aria.busca":"Apri ricerca","aria.idiomas":"Seleziona lingua","aria.menu":"Apri menu","aria.fechar":"Chiudi","aria.navPrincipal":"Navigazione principale","content.avaliar":"Valuta questo contenuto","content.compartilhar":"Condividi","content.salvar":"Salva","content.imprimir":"Stampa","content.leitura":"Ascolta","a11y.tituloModal":"Preferenze di accessibilita","a11y.fonteTitulo":"Dimensione carattere","a11y.contrasteTitulo":"Alto contrasto","a11y.temaTitulo":"Modalita scura","a11y.redefinir":"Ripristina tutto","cookie.aviso":"Informativa cookie","cookie.personalizar":"Personalizza","cookie.rejeitar":"Rifiuta non essenziali","cookie.aceiter":"Accetta tutti","cookie.salvar":"Salva preferenze","footer.direitos":"Tutti i diritti riservati.","hero.title":"Calcolatrici per Infermieri","hero.badge":"Piattaforma Globale","seo.h1":"Calcolatrici per Infermieri, Esami di Pratica e Scale Cliniche"},
    "nl": {"nav.inicio":"Home","nav.assistencia":"Zorg","nav.educacao":"Onderwijs","nav.faleconosco":"Contact","nav.pesquisa":"Zoeken","nav.idiomas":"Talen","nav.ferramentas":"Hulpmiddelen","nav.gestao":"Beheer","nav.recursos":"Bronnen","nav.institucional":"Institutioneel","nav.entrar":"Inloggen","nav.criar":"Account aanmaken","aria.busca":"Zoeken openen","aria.idiomas":"Taal selecteren","aria.menu":"Menu openen","aria.fechar":"Sluiten","aria.navPrincipal":"Hoofdnavigatie","content.avaliar":"Beoordeel deze inhoud","content.compartilhar":"Delen","content.salvar":"Opslaan","content.imprimir":"Afdrukken","content.leitura":"Luisteren","a11y.tituloModal":"Toegankelijkheidsvoorkeuren","a11y.fonteTitulo":"Lettergrootte","a11y.contrasteTitulo":"Hoog contrast","a11y.temaTitulo":"Donkere modus","a11y.redefinir":"Alles resetten","cookie.aviso":"Cookie-melding","cookie.personalizar":"Aanpassen","cookie.rejeitar":"Niet-essentiele weigeren","cookie.aceiter":"Alle accepteren","cookie.salvar":"Voorkeuren opslaan","footer.direitos":"Alle rechten voorbehouden.","hero.title":"Verpleegkundige Calculators","hero.badge":"Wereldwijd Platform","seo.h1":"Verpleegkundige Calculators, Oefeningen en Klinische Schalen"},
    "pl": {"nav.inicio":"Strona glowna","nav.assistencia":"Opieka","nav.educacao":"Edukacja","nav.faleconosco":"Kontakt","nav.pesquisa":"Szukaj","nav.idiomas":"Jezyki","nav.ferramentas":"Narzedzia","nav.gestao":"Zarzadzanie","nav.recursos":"Zasoby","nav.institucional":"Instytucjonalne","nav.entrar":"Zaloguj","nav.criar":"Utworz konto","aria.busca":"Otworz wyszukiwanie","aria.idiomas":"Wybierz jezyk","aria.menu":"Otworz menu","aria.fechar":"Zamknij","aria.navPrincipal":"Glowna nawigacja","content.avaliar":"Ocen te tresc","content.compartilhar":"Udostepnij","content.salvar":"Zapisz","content.imprimir":"Drukuj","content.leitura":"Sluchaj","a11y.tituloModal":"Preferencje dostepnosci","a11y.fonteTitulo":"Rozmiar czcionki","a11y.contrasteTitulo":"Wysoki kontrast","a11y.temaTitulo":"Tryb ciemny","a11y.redefinir":"Resetuj wszystko","cookie.aviso":"Informacja o plikach cookie","cookie.personalizar":"Dostosuj","cookie.rejeitar":"Odrzuc nieistotne","cookie.aceiter":"Akceptuj wszystkie","cookie.salvar":"Zapisz preferencje","footer.direitos":"Wszelkie prawa zastrzezone.","hero.title":"Kalkulatory Pielgniarskie","hero.badge":"Globalna Platforma","seo.h1":"Kalkulatory Pielgniarskie, Egzaminy Praktyczne i Skale Kliniczne"},
    "ru": {"nav.inicio":"Glavnaya","nav.assistencia":"Uhod","nav.educacao":"Obrazovanie","nav.faleconosco":"Kontakt","nav.pesquisa":"Poisk","nav.idiomas":"Yazyki","nav.ferramentas":"Instrumenty","nav.gestao":"Upravlenie","nav.recursos":"Resursy","nav.institucional":"Institucionalnoe","nav.entrar":"Voiti","nav.criar":"Sozdat akkaynt","aria.busca":"Otkryt poisk","aria.idiomas":"Vybrat yazyk","aria.menu":"Otkryt menyu","aria.fechar":"Zakryt","aria.navPrincipal":"Osnovnaya navigatsiya","content.avaliar":"Ocenit etot kontent","content.compartilhar":"Podelitsya","content.salvar":"Sohranit","content.imprimir":"Pechat","content.leitura":"Slushat","a11y.tituloModal":"Nastroyki dostupnosti","a11y.fonteTitulo":"Razmer shrifta","a11y.contrasteTitulo":"Vysokiy kontrast","a11y.temaTitulo":"Temnaya tema","a11y.redefinir":"Sbrosit vsyo","cookie.aviso":"Uvedomlenie o faylah cookie","cookie.personalizar":"Nastroit","cookie.rejeitar":"Otklonit neobyazatelnye","cookie.aceiter":"Prinyat vse","cookie.salvar":"Sohranit nastroyki","footer.direitos":"Vse prava zashchishcheny.","hero.title":"Kalkulyatory dlya medsester","hero.badge":"Globalnaya platforma","seo.h1":"Kalkulyatory dlya medsester, prakticheskie ekzameny i klinicheskie shkaly"},
    "tr": {"nav.inicio":"Ana Sayfa","nav.assistencia":"Bakim","nav.educacao":"Egitim","nav.faleconosco":"Iletisim","nav.pesquisa":"Ara","nav.idiomas":"Diller","nav.ferramentas":"Araclar","nav.gestao":"Yonetim","nav.recursos":"Kaynaklar","nav.institucional":"Kurumsal","nav.entrar":"Giris","nav.criar":"Hesap olustur","aria.busca":"Aramayi ac","aria.idiomas":"Dil sec","aria.menu":"Menuyu ac","aria.fechar":"Kapat","aria.navPrincipal":"Ana navigasyon","content.avaliar":"Bu icerigi degerlendir","content.compartilhar":"Paylas","content.salvar":"Kaydet","content.imprimir":"Yazdir","content.leitura":"Dinle","a11y.tituloModal":"Erisilebilirlik tercihleri","a11y.fonteTitulo":"Yazi tipi boyutu","a11y.contrasteTitulo":"Yuksek kontrast","a11y.temaTitulo":"Karanlik mod","a11y.redefinir":"Tumunu sifirla","cookie.aviso":"Cerez bildirimi","cookie.personalizar":"Ozellestir","cookie.rejeitar":"Zorunlu olmayanlari reddet","cookie.aceiter":"Tumunu kabul et","cookie.salvar":"Tercihleri kaydet","footer.direitos":"Tum haklari saklidir.","hero.title":"Hemsirelik Hesaplayicilari","hero.badge":"Kuresel Platform","seo.h1":"Hemsirelik Hesaplayicilari, Pratik Sinavlar ve Klinik Olcekler"},
    "ar": {"nav.inicio":"الرئيسية","nav.assistencia":"الرعاية","nav.educacao":"التعليم","nav.faleconosco":"اتصل بنا","nav.pesquisa":"بحث","nav.idiomas":"اللغات","nav.ferramentas":"الأدوات","nav.gestao":"الإدارة","nav.recursos":"الموارد","nav.institucional":"المؤسسي","nav.entrar":"تسجيل الدخول","nav.criar":"إنشاء حساب","aria.busca":"فتح البحث","aria.idiomas":"اختر اللغة","aria.menu":"فتح القائمة","aria.fechar":"إغلاق","aria.navPrincipal":"التنقل الرئيسي","content.avaliar":"تقييم هذا المحتوى","content.compartilhar":"مشاركة","content.salvar":"حفظ","content.imprimir":"طباعة","content.leitura":"استمع","a11y.tituloModal":"تفضيلات إمكانية الوصول","a11y.fonteTitulo":"حجم الخط","a11y.contrasteTitulo":"تباين عالٍ","a11y.temaTitulo":"الوضع الداكن","a11y.redefinir":"إعادة تعيين الكل","cookie.aviso":"إشعار ملفات تعريف الارتباط","cookie.personalizar":"تخصيص","cookie.rejeitar":"رفض غير الأساسية","cookie.aceiter":"قبول الكل","cookie.salvar":"حفظ التفضيلات","footer.direitos":"جميع الحقوق محفوظة.","hero.title":"حاسبات التمريض","hero.badge":"منصة عالمية","seo.h1":"حاسبات التمريض وامتحانات الممارسة والمقاييس السريرية"},
    "he": {"nav.inicio":"בית","nav.assistencia":"טיפול","nav.educacao":"חינוך","nav.faleconosco":"צור קשר","nav.pesquisa":"חיפוש","nav.idiomas":"שפות","nav.ferramentas":"כלים","nav.gestao":"ניהול","nav.recursos":"משאבים","nav.institucional":"מוסדי","nav.entrar":"התחבר","nav.criar":"צור חשבון","aria.busca":"פתח חיפוש","aria.idiomas":"בחר שפה","aria.menu":"פתח תפריט","aria.fechar":"סגור","aria.navPrincipal":"ניווט ראשי","content.avaliar":"דרג תוכן זה","content.compartilhar":"שתף","content.salvar":"שמור","content.imprimir":"הדפס","content.leitura":"האזן","a11y.tituloModal":"העדפות נגישות","a11y.fonteTitulo":"גודל גופן","a11y.contrasteTitulo":"ניגודיות גבוהה","a11y.temaTitulo":"מצב כהה","a11y.redefinir":"אפס הכל","cookie.aviso":"הודעת קוקיז","cookie.personalizar":"התאם אישית","cookie.rejeitar":"דחה לא חיוניים","cookie.aceiter":"קבל הכל","cookie.salvar":"שמור העדפות","footer.direitos":"כל הזכויות שמורות.","hero.title":"מחשבוני סיעוד","hero.badge":"פלטפורמה עולמית","seo.h1":"מחשבוני סיעוד, מבחני תרגול וסקלות קליניות"},
    "hi": {"nav.inicio":"होम","nav.assistencia":"देखभाल","nav.educacao":"शिक्षा","nav.faleconosco":"संपर्क","nav.pesquisa":"खोज","nav.idiomas":"भाषाएँ","nav.ferramentas":"उपकरण","nav.gestao":"प्रबंधन","nav.recursos":"संसाधन","nav.institucional":"संस्थागत","nav.entrar":"लॉगिन","nav.criar":"खाता बनाएँ","aria.busca":"खोज खोलें","aria.idiomas":"भाषा चुनें","aria.menu":"मेनू खोलें","aria.fechar":"बंद करें","aria.navPrincipal":"मुख्य नेविगेशन","content.avaliar":"इस सामग्री को रेट करें","content.compartilhar":"साझा करें","content.salvar":"सहेजें","content.imprimir":"प्रिंट","content.leitura":"सुनें","a11y.tituloModal":"पहुँच प्राथमिकताएँ","a11y.fonteTitulo":"फ़ॉन्ट आकार","a11y.contrasteTitulo":"उच्च कंट्रास्ट","a11y.temaTitulo":"डार्क मोड","a11y.redefinir":"सभी रीसेट करें","cookie.aviso":"कुकी सूचना","cookie.personalizar":"अनुकूलित करें","cookie.rejeitar":"गैर-आवश्यक अस्वीकार","cookie.aceiter":"सभी स्वीकार","cookie.salvar":"प्राथमिकताएँ सहेजें","footer.direitos":"सर्वाधिकार सुरक्षित।","hero.title":"नर्सिंग कैलकुलेटर","hero.badge":"वैश्विक प्लेटफ़ॉर्म","seo.h1":"नर्सिंग कैलकुलेटर, अभ्यास परीक्षा और नैदानिक स्केल"},
    "bn": {"nav.inicio":"হোম","nav.assistencia":"পরিচর্যা","nav.educacao":"শিক্ষা","nav.faleconosco":"যোগাযোগ","nav.pesquisa":"অনুসন্ধান","nav.idiomas":"ভাষা","nav.ferramentas":"সরঞ্জাম","nav.gestao":"ব্যবস্থাপনা","nav.recursos":"সম্পদ","nav.institucional":"প্রাতিষ্ঠানিক","nav.entrar":"লগইন","nav.criar":"অ্যাকাউন্ট তৈরি","aria.busca":"অনুসন্ধান খুলুন","aria.idiomas":"ভাষা নির্বাচন করুন","aria.menu":"মেনু খুলুন","aria.fechar":"বন্ধ","aria.navPrincipal":"প্রধান নেভিগেশন","content.avaliar":"এই বিষয়বস্তু মূল্যায়ন করুন","content.compartilhar":"শেয়ার","content.salvar":"সংরক্ষণ","content.imprimir":"মুদ্রণ","content.leitura":"শুনুন","a11y.tituloModal":"প্রবেশযোগ্যতা পছন্দ","a11y.fonteTitulo":"ফন্ট আকার","a11y.contrasteTitulo":"উচ্চ বৈপরীত্য","a11y.temaTitulo":"ডার্ক মোড","a11y.redefinir":"সব রিসেট","cookie.aviso":"কুকি বিজ্ঞপ্তি","cookie.personalizar":"কাস্টমাইজ","cookie.rejeitar":"অপ্রয়োজনীয় প্রত্যাখ্যান","cookie.aceiter":"সব গ্রহণ","cookie.salvar":"পছন্দ সংরক্ষণ","footer.direitos":"সর্বস্বত্ব সংরক্ষিত।","hero.title":"নার্সিং ক্যালকুলেটর","hero.badge":"বৈশ্বিক প্ল্যাটফর্ম","seo.h1":"নার্সিং ক্যালকুলেটর, অনুশীলন পরীক্ষা এবং ক্লিনিকাল স্কেল"},
    "zh-CN": {"nav.inicio":"首页","nav.assistencia":"护理","nav.educacao":"教育","nav.faleconosco":"联系我们","nav.pesquisa":"搜索","nav.idiomas":"语言","nav.ferramentas":"工具","nav.gestao":"管理","nav.recursos":"资源","nav.institucional":"机构","nav.entrar":"登录","nav.criar":"创建账户","aria.busca":"打开搜索","aria.idiomas":"选择语言","aria.menu":"打开菜单","aria.fechar":"关闭","aria.navPrincipal":"主导航","content.avaliar":"评价此内容","content.compartilhar":"分享","content.salvar":"保存","content.imprimir":"打印","content.leitura":"收听","a11y.tituloModal":"无障碍偏好设置","a11y.fonteTitulo":"字体大小","a11y.contrasteTitulo":"高对比度","a11y.temaTitulo":"深色模式","a11y.redefinir":"全部重置","cookie.aviso":"Cookie通知","cookie.personalizar":"自定义","cookie.rejeitar":"拒绝非必要","cookie.aceiter":"全部接受","cookie.salvar":"保存偏好","footer.direitos":"保留所有权利。","hero.title":"护理计算器","hero.badge":"全球平台","seo.h1":"护理计算器、练习考试和临床量表"},
    "zh-TW": {"nav.inicio":"首頁","nav.assistencia":"護理","nav.educacao":"教育","nav.faleconosco":"聯絡我們","nav.pesquisa":"搜尋","nav.idiomas":"語言","nav.ferramentas":"工具","nav.gestao":"管理","nav.recursos":"資源","nav.institucional":"機構","nav.entrar":"登入","nav.criar":"建立帳戶","aria.busca":"開啟搜尋","aria.idiomas":"選擇語言","aria.menu":"開啟選單","aria.fechar":"關閉","aria.navPrincipal":"主導航","content.avaliar":"評價此內容","content.compartilhar":"分享","content.salvar":"儲存","content.imprimir":"列印","content.leitura":"聆聽","a11y.tituloModal":"無障礙偏好設定","a11y.fonteTitulo":"字型大小","a11y.contrasteTitulo":"高對比度","a11y.temaTitulo":"深色模式","a11y.redefinir":"全部重設","cookie.aviso":"Cookie通知","cookie.personalizar":"自訂","cookie.rejeitar":"拒絕非必要","cookie.aceiter":"全部接受","cookie.salvar":"儲存偏好","footer.direitos":"保留所有權利。","hero.title":"護理計算器","hero.badge":"全球平台","seo.h1":"護理計算器、練習考試和臨床量表"},
    "ja": {"nav.inicio":"ホーム","nav.assistencia":"ケア","nav.educacao":"教育","nav.faleconosco":"お問い合わせ","nav.pesquisa":"検索","nav.idiomas":"言語","nav.ferramentas":"ツール","nav.gestao":"管理","nav.recursos":"リソース","nav.institucional":"概要","nav.entrar":"ログイン","nav.criar":"アカウント作成","aria.busca":"検索を開く","aria.idiomas":"言語を選択","aria.menu":"メニューを開く","aria.fechar":"閉じる","aria.navPrincipal":"メインナビゲーション","content.avaliar":"このコンテンツを評価","content.compartilhar":"共有","content.salvar":"保存","content.imprimir":"印刷","content.leitura":"聞く","a11y.tituloModal":"アクセシビリティ設定","a11y.fonteTitulo":"フォントサイズ","a11y.contrasteTitulo":"ハイコントラスト","a11y.temaTitulo":"ダークモード","a11y.redefinir":"すべてリセット","cookie.aviso":"Cookie通知","cookie.personalizar":"カスタマイズ","cookie.rejeitar":"非必須を拒否","cookie.aceiter":"すべて接受","cookie.salvar":"設定を保存","footer.direitos":"全著作権所有。","hero.title":"看護計算機","hero.badge":"グローバルプラットフォーム","seo.h1":"看護計算機、練習試験と臨床スケール"},
    "ko": {"nav.inicio":"홈","nav.assistencia":"간호","nav.educacao":"교육","nav.faleconosco":"문의","nav.pesquisa":"검색","nav.idiomas":"언어","nav.ferramentas":"도구","nav.gestao":"관리","nav.recursos":"자료","nav.institucional":"소개","nav.entrar":"로그인","nav.criar":"계정 만들기","aria.busca":"검색 열기","aria.idiomas":"언어 선택","aria.menu":"메뉴 열기","aria.fechar":"닫기","aria.navPrincipal":"주요 내비게이션","content.avaliar":"이 콘텐츠 평가","content.compartilhar":"공유","content.salvar":"저장","content.imprimir":"인쇄","content.leitura":"듣기","a11y.tituloModal":"접근성 환경설정","a11y.fonteTitulo":"글꼴 크기","a11y.contrasteTitulo":"고대비","a11y.temaTitulo":"다크 모드","a11y.redefinir":"모두 재설정","cookie.aviso":"쿠키 알림","cookie.personalizar":"사용자 정의","cookie.rejeitar":"비필수 거부","cookie.aceiter":"모두 수락","cookie.salvar":"환경설정 저장","footer.direitos":"모든 권리 보유.","hero.title":"간호 계산기","hero.badge":"글로벌 플랫폼","seo.h1":"간호 계산기, 연습 시험 및 임상 척도"},
    "vi": {"nav.inicio":"Trang chinh","nav.assistencia":"Cham soc","nav.educacao":"Giao duc","nav.faleconosco":"Lien he","nav.pesquisa":"Tim kiem","nav.idiomas":"Ngon ngu","nav.ferramentas":"Cong cu","nav.gestao":"Quan ly","nav.recursos":"Tai nguyen","nav.institucional":"To chuc","nav.entrar":"Dang nhap","nav.criar":"Tao tai khoan","aria.busca":"Mo tim kiem","aria.idiomas":"Chon ngon ngu","aria.menu":"Mo menu","aria.fechar":"Dong","aria.navPrincipal":" Dieu huong chinh","content.avaliar":"Danh gia noi dung nay","content.compartilhar":"Chia se","content.salvar":"Luu","content.imprimir":"In","content.leitura":"Nghe","a11y.tituloModal":"Tuy chon kha nang tiep can","a11y.fonteTitulo":"Kich thuoc phong chu","a11y.contrasteTitulo":"Do tuong phan cao","a11y.temaTitulo":"Che do toi","a11y.redefinir":"Dat lai tat ca","cookie.aviso":"Thong bao cookie","cookie.personalizar":"Tuy chinh","cookie.rejeitar":"Tu choi khong can thiet","cookie.aceiter":"Chap nhan tat ca","cookie.salvar":"Luu tuy chon","footer.direitos":"Bao luu moi quyen.","hero.title":"May tinh Dieu duong","hero.badge":"Nen tang Toan cau","seo.h1":"May tinh Dieu duong, Bai thi thuc hanh va Thang do Lam sang"},
    "th": {"nav.inicio":"หน้าแรก","nav.assistencia":"การดูแล","nav.educacao":"การศึกษา","nav.faleconosco":"ติดต่อ","nav.pesquisa":"ค้นหา","nav.idiomas":"ภาษา","nav.ferramentas":"เครื่องมือ","nav.gestao":"การจัดการ","nav.recursos":"ทรัพยากร","nav.institucional":"องค์กร","nav.entrar":"เข้าสู่ระบบ","nav.criar":"สร้างบัญชี","aria.busca":"เปิดการค้นหา","aria.idiomas":"เลือกภาษา","aria.menu":"เปิดเมนู","aria.fechar":"ปิด","aria.navPrincipal":"การนำทางหลัก","content.avaliar":"ประเมินเนื้อหา","content.compartilhar":"แชร์","content.salvar":"บันทึก","content.imprimir":"พิมพ์","content.leitura":"ฟัง","a11y.tituloModal":"การตั้งค่าการเข้าถึง","a11y.fonteTitulo":"ขนาดตัวอักษร","a11y.contrasteTitulo":"ความคมชัดสูง","a11y.temaTitulo":"โหมดมืด","a11y.redefinir":"รีเซ็ตทั้งหมด","cookie.aviso":"การแจ้งเตือนคุกกี้","cookie.personalizar":"ปรับแต่ง","cookie.rejeitar":"ปฏิเสธที่ไม่จำเป็น","cookie.aceiter":"ยอมรับทั้งหมด","cookie.salvar":"บันทึกการตั้งค่า","footer.direitos":"สงวนลิขสิทธิ์ทั้งหมด","hero.title":"เครื่องคำนวณพยาบาล","hero.badge":"แพลตฟอร์มระดับโลก","seo.h1":"เครื่องคำนวณพยาบาล, การสอบฝึกหัด และมาตรวัดทางคลินิก"},
    "id": {"nav.inicio":"Beranda","nav.assistencia":"Asuhan","nav.educacao":"Pendidikan","nav.faleconosco":"Kontak","nav.pesquisa":"Cari","nav.idiomas":"Bahasa","nav.ferramentas":"Alat","nav.gestao":"Manajemen","nav.recursos":"Sumber Daya","nav.institucional":"Institusional","nav.entrar":"Masuk","nav.criar":"Buat akun","aria.busca":"Buka pencarian","aria.idiomas":"Pilih bahasa","aria.menu":"Buka menu","aria.fechar":"Tutup","aria.navPrincipal":"Navigasi utama","content.avaliar":"Nilai konten ini","content.compartilhar":"Bagikan","content.salvar":"Simpan","content.imprimir":"Cetak","content.leitura":"Dengar","a11y.tituloModal":"Preferensi aksesibilitas","a11y.fonteTitulo":"Ukuran font","a11y.contrasteTitulo":"Kontras tinggi","a11y.temaTitulo":"Mode gelap","a11y.redefinir":"Atur ulang semua","cookie.aviso":"Pemberitahuan cookie","cookie.personalizar":"Sesuaikan","cookie.rejeitar":"Tolak non-esensial","cookie.aceiter":"Terima semua","cookie.salvar":"Simpan preferensi","footer.direitos":"Hak cipta dilindungi.","hero.title":"Kalkulator Keperawatan","hero.badge":"Platform Global","seo.h1":"Kalkulator Keperawatan, Ujian Latihan dan Skala Klinis"},
    "ms": {"nav.inicio":"Laman utama","nav.assistencia":"Penjagaan","nav.educacao":"Pendidikan","nav.faleconosco":"Hubungi","nav.pesquisa":"Cari","nav.idiomas":"Bahasa","nav.ferramentas":"Alat","nav.gestao":"Pengurusan","nav.recursos":"Sumber","nav.institucional":"Institusi","nav.entrar":"Log masuk","nav.criar":"Buat akaun","aria.busca":"Buka carian","aria.idiomas":"Pilih bahasa","aria.menu":"Buka menu","aria.fechar":"Tutup","aria.navPrincipal":"Navigasi utama","content.avaliar":"Nilai kandungan ini","content.compartilhar":"Kongsi","content.salvar":"Simpan","content.imprimir":"Cetak","content.leitura":"Dengar","a11y.tituloModal":"Keutamaan kebolehcapaian","a11y.fonteTitulo":"Saiz fon","a11y.contrasteTitulo":"Kontras tinggi","a11y.temaTitulo":"Mod gelap","a11y.redefinir":"Set semula semua","cookie.aviso":"Notis cookie","cookie.personalizar":"Sesuaikan","cookie.rejeitar":"Tolak bukan penting","cookie.aceiter":"Terima semua","cookie.salvar":"Simpan keutamaan","footer.direitos":"Hak cipta terpelihara.","hero.title":"Kalkulator Kejururawatan","hero.badge":"Platform Global","seo.h1":"Kalkulator Kejururawatan, Peperiksaan Latihan dan Skala Klinikal"},
    "tl": {"nav.inicio":"Home","nav.assistencia":"Pangangalaga","nav.educacao":"Edukasyon","nav.faleconosco":"Makipag-ugnayan","nav.pesquisa":"Maghanap","nav.idiomas":"Mga Wika","nav.ferramentas":"Mga Tool","nav.gestao":"Pamamahala","nav.recursos":"Resources","nav.institucional":"Institusyonal","nav.entrar":"Mag-login","nav.criar":"Gumawa ng account","aria.busca":"Buksan ang paghahanap","aria.idiomas":"Piliin ang wika","aria.menu":"Buksan ang menu","aria.fechar":"Isara","aria.navPrincipal":"Pangunahing nabigasyon","content.avaliar":"I-rate ang nilalaman","content.compartilhar":"Ibahagi","content.salvar":"I-save","content.imprimir":"I-print","content.leitura":"Makinig","a11y.tituloModal":"Mga kagustuhan sa accessibility","a11y.fonteTitulo":"Laki ng font","a11y.contrasteTitulo":"Mataas na contrast","a11y.temaTitulo":"Dark mode","a11y.redefinir":"I-reset lahat","cookie.aviso":"Cookie notice","cookie.personalizar":"I-customize","cookie.rejeitar":"Tanggihan ang non-essential","cookie.aceiter":"Tanggapin lahat","cookie.salvar":"I-save ang preferences","footer.direitos":"Lahat ng karapatang nakalaan.","hero.title":"Nursing Calculators","hero.badge":"Global Platform","seo.h1":"Nursing Calculators, Practice Exams at Clinical Scales"},
    "sw": {"nav.inicio":"Mwanzo","nav.assistencia":"Huduma","nav.educacao":"Elimu","nav.faleconosco":"Wasiliana","nav.pesquisa":"Tafuta","nav.idiomas":"Lugha","nav.ferramentas":"Zana","nav.gestao":"Usimamizi","nav.recursos":"Rasilimali","nav.institucional":"Taasisi","nav.entrar":"Ingia","nav.criar":"Fungua akaunti","aria.busca":"Fungua utafutaji","aria.idiomas":"Chagua lugha","aria.menu":"Fungua menyu","aria.fechar":"Funga","aria.navPrincipal":"Uelekeaji mkuu","content.avaliar":"Kadiria maudhui haya","content.compartilhar":"Shiriki","content.salvar":"Hifadhi","content.imprimir":"Chapisha","content.leitura":"Sikiliza","a11y.tituloModal":"Mapendeleo ya ufikiaji","a11y.fonteTitulo":"Ukubwa wa fonti","a11y.contrasteTitulo":"Mkazo mkubwa","a11y.temaTitulo":"Modi ya giza","a11y.redefinir":"Seti upya zote","cookie.aviso":"Taarifa ya cookie","cookie.personalizar":"Badilisha","cookie.rejeitar":"Kataa zisizo muhimu","cookie.aceiter":"Kubali zote","cookie.salvar":"Hifadhi mapendeleo","footer.direitos":"Haki zote zimehifadhiwa.","hero.title":"Viwango vya Nursing","hero.badge":"Jukwaa la Kimataifa","seo.h1":"Viwango vya Nursing, Mitihani ya Mazoezi na Skeli za Kitabibu"},
    "am": {"nav.inicio":"መነሻ","nav.assistencia":"እንክእከ","nav.educacao":"ትምህርት","nav.faleconosco":"አግኙን","nav.pesquisa":"ፈልግ","nav.idiomas":"ቋንቋዎች","nav.ferramentas":"መሳሪያዎች","nav.gestao":"አስተዳደር","nav.recursos":"ሀብቶች","nav.institucional":"ተቋማዊ","nav.entrar":"ግባ","nav.criar":"መለያ ፍጠር","aria.busca":"ፍለጋ ክፈት","aria.idiomas":"ቋንቋ ምረጥ","aria.menu":"ሜኑ ክፈት","aria.fechar":"ዝጋ","aria.navPrincipal":"ዋና አሰጣጥ","content.avaliar":"ይህን ይዘት ደርድር","content.compartilhar":"አጋራ","content.salvar":"አስቀምጥ","content.imprimir":"አትም","content.leitura":"ድምፅ ያድምጡ","a11y.tituloModal":"የተደራረኝ ምርጫዎች","a11y.fonteTitulo":"የፊደል መጠን","a11y.contrasteTitulo":"ከፍተኛ ንፅፅር","a11y.temaTitulo":"ጨለማ ሁነታ","a11y.redefinir":"ሁሉንም ዳግም አስጀምር","cookie.aviso":"የኩኪ ማስታወቂያ","cookie.personalizar":"አብጅ","cookie.rejeitar":"አስፈላጊ ያልሆኑን ውጣ","cookie.aceiter":"ሁሉንም ተቀበል","cookie.salvar":"ምርጫዎችን አስቀምጥ","footer.direitos":"መብቶች ተጠብቀዋል።","hero.title":"የ Nursing ማስሊያዎች","hero.badge":"ዓለም አቀፍ መድረክ","seo.h1":"የ Nursing ማስሊያዎች፣ የልምምድ ፈተናዎች እና ክሊኒካዊ ሚዛኖች"},
    "el": {"nav.inicio":"Αρχική","nav.assistencia":"Φροντίδα","nav.educacao":"Εκπαίδευση","nav.faleconosco":"Επικοινωνία","nav.pesquisa":"Αναζήτηση","nav.idiomas":"Γλώσσες","nav.ferramentas":"Εργαλεία","nav.gestao":"Διαχείριση","nav.recursos":"Πόροι","nav.institucional":"Ιδρυμαικό","nav.entrar":"Σύνδεση","nav.criar":"Δημιουργία λογαριασμού","aria.busca":"Άνοιγμα αναζήτησης","aria.idiomas":"Επιλογή γλώσσας","aria.menu":"Άνοιγμα μενού","aria.fechar":"Κλείσιμο","aria.navPrincipal":"Κύρια πλοήγηση","content.avaliar":"Αξιολογήστε αυτό το περιεχόμενο","content.compartilhar":"Κοινοποίηση","content.salvar":"Αποθήκευση","content.imprimir":"Εκτύπωση","content.leitura":"Ακούστε","a11y.tituloModal":"Προτιμήσεις προσβασιμότητας","a11y.fonteTitulo":"Μέγεθος γραμματοσειράς","a11y.contrasteTitulo":"Υψηλή αντίθεση","a11y.temaTitulo":"Σκοτεινή λειτουργία","a11y.redefinir":"Επαναφορά όλων","cookie.aviso":"Ειδοποίηση cookies","cookie.personalizar":"Προσαρμογή","cookie.rejeitar":"Απόρριψη μη απαραίτητων","cookie.aceiter":"Αποδοχή όλων","cookie.salvar":"Αποθήκευση προτιμήσεων","footer.direitos":"Με επιφύλαξη παντός δικαιώματος.","hero.title":"Αριθμομηχανές Νοσηλευτικής","hero.badge":"Παγκόσμια Πλατφόρμα","seo.h1":"Αριθμομηχανές Νοσηλευτικής, Διαγωνίσματα και Κλινικές Κλίμακες"},
    "ro": {"nav.inicio":"Acasa","nav.assistencia":"Ingrijire","nav.educacao":"Educatie","nav.faleconosco":"Contact","nav.pesquisa":"Cauta","nav.idiomas":"Limbi","nav.ferramentas":"Instrumente","nav.gestao":"Management","nav.recursos":"Resurse","nav.institucional":"Institutional","nav.entrar":"Conectare","nav.criar":"Creeaza cont","aria.busca":"Deschide cautarea","aria.idiomas":"Selecteaza limba","aria.menu":"Deschide meniul","aria.fechar":"Inchide","aria.navPrincipal":"Navigare principala","content.avaliar":"Evalueaza acest continut","content.compartilhar":"Distribuie","content.salvar":"Salveaza","content.imprimir":"Tipareste","content.leitura":"Asculta","a11y.tituloModal":"Preferinte de accesibilitate","a11y.fonteTitulo":"Marime font","a11y.contrasteTitulo":"Contrast ridicat","a11y.temaTitulo":"Mod intunecat","a11y.redefinir":"Reseteaza tot","cookie.aviso":"Notificare cookies","cookie.personalizar":"Personalizeaza","cookie.rejeitar":"Respinge non-esentiale","cookie.aceiter":"Accepta toate","cookie.salvar":"Salveaza preferintele","footer.direitos":"Toate drepturile rezervate.","hero.title":"Calculatoare de Nursing","hero.badge":"Platforma Globala","seo.h1":"Calculatoare de Nursing, Examen de Practica si Scale Clinice"},
    "hu": {"nav.inicio":"Foldal","nav.assistencia":"Apolas","nav.educacao":"Oktatas","nav.faleconosco":"Kapcsolat","nav.pesquisa":"Kereses","nav.idiomas":"Nyelvek","nav.ferramentas":"Eszkozok","nav.gestao":"Menedzsment","nav.recursos":"Erforrasok","nav.institucional":"Intezmenyes","nav.entrar":"Bejelentkezes","nav.criar":"Fiok letrehozasa","aria.busca":"Kereses megnyitasa","aria.idiomas":"Nyelv kivalasztasa","aria.menu":"Menu megnyitasa","aria.fechar":"Bezaras","aria.navPrincipal":"Fo navigacio","content.avaliar":"Ertekeld ezt a tartalmat","content.compartilhar":"Megosztas","content.salvar":"Mentes","content.imprimir":"Nyomtatas","content.leitura":"Hallgat","a11y.tituloModal":"Akadalymentességi beallitasok","a11y.fonteTitulo":"Betumeret","a11y.contrasteTitulo":"Magas kontraszt","a11y.temaTitulo":"Sotet mod","a11y.redefinir":"Osszes visszaallitasa","cookie.aviso":"Cookie ertesites","cookie.personalizar":"Testreszabas","cookie.rejeitar":"Nem esszencialis elutasitasa","cookie.aceiter":"Osszes elfogadasa","cookie.salvar":"Beallitasok mentese","footer.direitos":"Minden jog fenntartva.","hero.title":"Apolasi Szamologépek","hero.badge":"Globalis Platform","seo.h1":"Apolasi Szamologépek, Gyakorlo Vizsgak es Klinikai Skalak"},
    "cs": {"nav.inicio":"Domu","nav.assistencia":"Péce","nav.educacao":"Vzdelavani","nav.faleconosco":"Kontakt","nav.pesquisa":"Hledat","nav.idiomas":"Jazyky","nav.ferramentas":"Nastroje","nav.gestao":"Management","nav.recursos":"Zdroje","nav.institucional":"Institucionalni","nav.entrar":"Prihlasit","nav.criar":"Vytvorit ucet","aria.busca":"Otevrit hledani","aria.idiomas":"Vybrat jazyk","aria.menu":"Otevrit menu","aria.fechar":"Zavrit","aria.navPrincipal":"Hlavní navigace","content.avaliar":"Ohodnotit tento obsah","content.compartilhar":"Sdílet","content.salvar":"Ulozit","content.imprimir":"Tisk","content.leitura":"Poslouchat","a11y.tituloModal":"Predvolby pristupnosti","a11y.fonteTitulo":"Velikost pisma","a11y.contrasteTitulo":"Vysoky kontrast","a11y.temaTitulo":"Tmavy rezim","a11y.redefinir":"Obnovit vse","cookie.aviso":"Oznámeni o cookies","cookie.personalizar":"Prizpusobit","cookie.rejeitar":"Odmítnout nepodstatne","cookie.aceiter":"Príjmout vse","cookie.salvar":"Ulozit predvolby","footer.direitos":"Všechna práva vyhrazena.","hero.title":"Osetrovatelske Kalkulacky","hero.badge":"Globalni Platforma","seo.h1":"Osetrovatelske Kalkulacky, Cvicne Zkousky a Klinicke Skaly"},
    "sv": {"nav.inicio":"Hem","nav.assistencia":"Vård","nav.educacao":"Utbildning","nav.faleconosco":"Kontakt","nav.pesquisa":"Sök","nav.idiomas":"Språk","nav.ferramentas":"Verktyg","nav.gestao":"Ledning","nav.recursos":"Resurser","nav.institucional":"Institutionellt","nav.entrar":"Logga in","nav.criar":"Skapa konto","aria.busca":"Öppna sökning","aria.idiomas":"Välj språk","aria.menu":"Öppna meny","aria.fechar":"Stäng","aria.navPrincipal":"Huvudnavigering","content.avaliar":"Betygsätt detta innehåll","content.compartilhar":"Dela","content.salvar":"Spara","content.imprimir":"Skriv ut","content.leitura":"Lyssna","a11y.tituloModal":"Tillgänglighetsinställningar","a11y.fonteTitulo":"Teckenstorlek","a11y.contrasteTitulo":"Hög kontrast","a11y.temaTitulo":"Mörkt läge","a11y.redefinir":"Återställ alla","cookie.aviso":"Cookie-meddelande","cookie.personalizar":"Anpassa","cookie.rejeitar":"Avvisa icke-esentiella","cookie.aceiter":"Acceptera alla","cookie.salvar":"Spara inställningar","footer.direitos":"Alla rättigheter förbehålls.","hero.title":"Omvårdnadskalkylatorer","hero.badge":"Global plattform","seo.h1":"Omvårdnadskalkylatorer, övningsprov och kliniska skalor"},
}

def generate_language_file(lang_code, translations):
    result = copy.deepcopy(EN)
    for key, value in translations.items():
        if key in result:
            result[key] = value
    return result

os.makedirs('i18n', exist_ok=True)

# Generate full Spanish (es) — already exists, skip
# Generate full French (fr)
for code in ["fr"]:
    data = generate_language_file(code, COMPACT_UI[code])
    with open(f"i18n/{code}.json", 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  ✅ {code}.json — {len(COMPACT_UI[code])} keys translated, {len(EN)} total")

# Generate all compact languages
for code, translations in COMPACT_UI.items():
    if code == "fr":
        continue  # already done
    data = generate_language_file(code, translations)
    with open(f"i18n/{code}.json", 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  ✅ {code}.json — {len(translations)} keys translated, {len(EN)} total")

print(f"\n✅ Generated {len(COMPACT_UI)} language files")
print(f"   Total: 30 languages (pt-BR native + en + es + {len(COMPACT_UI)} generated)")
